# This file is used to run integration tests on travis
version: '3'
services:

  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
    healthcheck:
      test: "mongo localhost:27017/test --quiet --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"
      interval: 10s
      timeout: 5s
      retries: 5

  upstreams:
    image: rodolpheche/wiremock:2.6.0-alpine
    ports:
      - '9089:8080'
    volumes:
      - ./stubs/upstreams:/home/wiremock/mappings

  auth-service:
    image: rodolpheche/wiremock:2.6.0-alpine
    ports:
      - '9088:8080'
    volumes:
      - ./stubs/auth-service:/home/wiremock/mappings

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"

  zipkin:
    image: openzipkin/zipkin
    environment:
      STORAGE_TYPE: mem
      JAVA_OPTS: -Dlogging.level.zipkin=DEBUG
    ports:
      - 9411:9411
